### ISSUE TITLE
wiki extension

### ISSUE THREAD

**Issue by malvela** [Estimation-product-quality-features/FeedAI#16]
![grafik](https://user-images.githubusercontent.com/68553692/153562975-ead332b2-aa40-45c0-baf3-e98c32aa9d85.png)

Das laden der Seite klappt nicht ganz

**Comment by malvela** [comment]
Extension of wiki part in process

**Comment by Hannes-G** [comment]
Muss noch überarbeitet werden

**Comment by Hannes-G** [comment]
Updated, allerdings noch nicht fertig
